metadata:
  name: ctfd
  namespace: ctfd
spec:
  project: default
    
  source:
    repoURL: https://github.com/deigott/CTFd.git
    targetRevision: HEAD
    path: CTFd
  destination:
    server: https://kubernetes.default.svc
    namespace: ctfd
      
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
        
    automated:
      selfHeal: true
      purne: true
